# Generated by Django 4.1.5 on 2023-01-26 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_user_crawler'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_crawler',
            new_name='crawler',
        ),
    ]
